openapi: 3.1.0
info:
  title: DataForSEO MCP Plugin
  description: MCP endpoint that accepts JSON-RPC calls
  version: "1.0.0"

servers:
  - url: https://mcp-server-typescript-production.up.railway.app
    description: MCP base URL

paths:
  /mcp:
    post:
      summary: Call MCP tools via JSON-RPC
      operationId: getSerpLiveAdvanced               # שם חופשי עבור הבילדר
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:        { type: string, enum: ["2.0"] }
                id:             { oneOf: [{type: string}, {type: integer}] }
                method:         { type: string, example: getSerpLiveAdvanced }
                params:
                  type: object
                  properties:
                    keyword:       { type: string,  example: "apple" }
                    location_code: { type: integer, example: 2840 }
                    language_code: { type: string,  example: "en" }
                  required: [keyword, location_code, language_code]
              required: [jsonrpc, id, method, params]

      responses:
        "200":
          description: MCP server response (JSON or SSE stream)
          content:
            application/json:              # ← JSON רגיל
              schema:
                type: object
                properties: {}
                additionalProperties: true
            text/event-stream:             # ← זרם SSE לתשובות ארוכות/חלקיות
              schema:
                type: string               # גוף SSE הוא טקסט
                description: Server-Sent Events stream
