openapi: 3.1.0
info:
  title: DataForSEO MCP Plugin
  description: MCP server that connects ChatGPT to DataForSEO
  version: "1.0.0"

servers:
  - url: https://mcp-server-typescript-production.up.railway.app/

paths:
  /serp/live/advanced:
    post:
      summary: Get live SERP data from DataForSEO
      operationId: getSerpLiveAdvanced
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                  example: "apple"
                location_code:
                  type: integer
                  example: 2840
                language_code:
                  type: string
                  example: "en"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
